version: 2
executorType: machine
jobs:
  build:
    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: mvn -s settings.xml clean deploy
workflows:
  version: 2
  build:
    jobs:
      - build
