version: 2
jobs:
   build:
      machine:
         image: ubuntu-1604:201903-01
         docker_layer_caching: true
      working_directory: ~/repo
      environment:
         MAVEN_OPTS: -Xmx3200m
      steps:
      - checkout
      -  run: mvn -s settings.xml clean deploy
workflows:
   version: 2
   build:
      jobs:
      - build